#### general settings
name: train_rebuttal_smallNet_ch32_blocks1
use_tb_logger: true
model: LLFlow
distortion: sr
scale: 1
gpu_ids: [0]
dataset: LoL
optimize_all_z: false
cond_encoder: ConEncoder1
train_gt_ratio: 0.2
avg_color_map: false

concat_histeq: true
histeq_as_input: false
concat_color_map: false
gray_map: false # concat 1-input.mean(dim=1) to the input

align_condition_feature: false
align_weight: 0.001
align_maxpool: true

to_yuv: false

encode_color_map: false
le_curve: false
# sigmoid_output: true

#### datasets
datasets:
  train:
    root: /home/zhaolab/zcm/home/data/CMapTrainingData/170614plc1p1/BuildTrainingDataset/prepareforZelin/TrainingandEvaluation_20230925/Z
    quant: 32
    use_shuffle: true
    n_workers: 1  # per GPU
    batch_size: 16
    use_flip: true
    color: RGB
    use_crop: true
    GT_size: 160 # 192
    noise_prob: 0
    noise_level: 5
    log_low: true
    gamma_aug: false

  val:
    root: /home/zhaolab/zcm/home/data/CMapTrainingData/170614plc1p1/BuildTrainingDataset/prepareforZelin/TrainingandEvaluation_20230925/Z
    n_workers: 1
    quant: 32
    n_max: 20
    batch_size: 1 # must be 1
    log_low: true

#### Test Settings
# dataroot_GT: D:\LOLdataset\eval15\high
# dataroot_LR: D:\LOLdataset\eval15\low
dataroot_unpaired: ./output_folder/Z/
#/home/zhaolab/zcm/home/data/CMapTrainingData/170614plc1p1/BuildTrainingDataset/trainingdata-xi/our485/low
#/home/zhaolab/zcm/home/data/CMapTrainingData/170614plc1p1/BuildTrainingDataset/Mem_database/200113plc1p2_178_rawMemb
#dataroot_GT: /home/zhaolab/zcm/home/data/CMapTrainingData/170614plc1p1/BuildTrainingDataset/Mem_database_1/eval15/high
#dataroot_LR: /home/zhaolab/zcm/home/data/CMapTrainingData/170614plc1p1/BuildTrainingDataset/Mem_database_1/eval15/low
#model_path: ./model_parameters/Z_axis.pth
model_path: ./model_parameters/Z_axis.pth
heat: 0 # This is the standard deviation of the latent vectors

#### network structures
network_G:
  which_model_G: LLFlow
  in_nc: 3
  out_nc: 3
  nf: 32
  nb: 4 #  12 for our low light encoder, 23 for LLFlow
  train_RRDB: false
  train_RRDB_delay: 0.5

  flow:
    K: 4 # 24.49 psnr用的12 # 16
    L: 3 # 4
    noInitialInj: true
    coupling: CondAffineSeparatedAndCond
    additionalFlowNoAffine: 2
    conditionInFeaDim: 64
    split:
      enable: false
    fea_up0: true
    stackRRDB:
      blocks: [1]
      concat: true

#### path
path:
  # pretrain_model_G: ../pretrained_models/RRDB_DF2K_8X.pth
  strict_load: true
  resume_state: auto

#### training settings: learning rate scheme, loss
train:
  manual_seed: 10
  lr_G: !!float 4e-4 # normalizing flow 5e-4; l1 loss train 5e-5
  weight_decay_G: 0 # 1e-5 # 5e-5 # 1e-5
  beta1: 0.9
  beta2: 0.99
  lr_scheme: MultiStepLR
  warmup_iter: -1  # no warm up
  lr_steps_rel: [ 0.15, 0.3, 0.45, 0.6 ] # [0.2, 0.35, 0.5, 0.65, 0.8, 0.95]  # [ 0.5, 0.75, 0.9, 0.95 ]
  lr_gamma: 0.5

  weight_l1: 0
  # flow_warm_up_iter: -1
  weight_fl: 1

  niter: 10000 #200000
  val_freq: 100 # 200

#### validation settings
val:
  # heats: [ 0.0, 0.5, 0.75, 1.0 ]
  n_sample: 4

test:
  heats: [ 0.0, 0.7, 0.8, 0.9 ]

#### logger
logger:
  # Debug print_freq: 100
  print_freq: 100
  save_checkpoint_freq: !!float 1e3
